"""empty message

Revision ID: 4e5fa5c5c428
Revises: 580ca79ee459
Create Date: 2015-08-26 21:51:08.356295

"""

# revision identifiers, used by Alembic.
revision = '4e5fa5c5c428'
down_revision = '580ca79ee459'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_column('user', 'nume')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nume', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'name')
    ### end Alembic commands ###
